# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-pouchdb-lucene
    git_repository: https://github.com/the-t-in-rtf/gpii-pouchdb-lucene.git
    git_branch: GPII-1785
    software_stack: nodejs
    folder:
      dest: /app/gpii-pouchdb-lucene
    run_in: fedora
    deploy: false
    setup:
      - sudo yum -y install java-1.8.0-openjdk-devel.x86_64
      - sudo yum -y install maven.noarch
      - sudo npm install -g yarn
      - yarn install
    test_cmds:
      - TMPDIR=/tmp yarn test
