app_name: gpii-pouchdb-lucene

git_repository: https://github.com/the-t-in-rtf/gpii-pouchdb-lucene.git

email: tony@raisingthefloor.org

env_runtime: linux

app_start_service: false

software_stack: nodejs

software_stack_version: 4.3.1

setup:
  - sudo yum -y install maven
  - npm install

commands:
  - npm test