# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
app_name: gpii-pouchdb-lucene

git_repository: https://github.com/the-t-in-rtf/gpii-pouchdb-lucene.git

email: tony@raisingthefloor.org

env_runtime: linux

app_start_service: false

software_stack: nodejs

software_stack_version: lts

setup:
  - sudo yum -y install java-1.8.0-openjdk-devel.x86_64
  - sudo yum -y install maven.noarch
  - npm install

commands:
  - TMPDIR=/tmp npm test