language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=0.12 JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true"

install:
  - nvm install $NODE_VERSION
  - npm install

script:
  - nvm use $NODE_VERSION
  - npm test

cache:
  directories:
  - $HOME/.m2

after_failure:
 - netstat -tanl