language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=6 JAVA_OPTS="-Djava.net.preferIPv4Stack=true"

install:
  - nvm install $NODE_VERSION
  - npm install -g yarn
  - npm install

script:
  - nvm use $NODE_VERSION
  - npm test

cache:
  directories:
  - $HOME/.m2

after_failure:
 - netstat -tanl